type:docs:
  - "docs/**/*.md"
  - "community/**/*.md"
  - "ecosystem/**/*.md"
area:dependencies:
  - "package.json"
  - "pnpm-lock.yaml"
  - "yarn.lock"
type:maintenance:
  - "functions/**"
  - "src/**"
  - "lib/**"
  - ".editorconfig"
  - ".gitattributes"
  - ".gitignore"
  - ".github/CODEOWNERS"
  - ".github/*rc"
  - ".github/*.md"
  - ".github/*.yml"
  - ".github/*.yaml"
  - ".github/*.json"
  - ".markdownlint.json"
  - ".prettierrc"
  - ".prettierignore"
  - ".trunk/*.yaml"
  - ".trunk/*.json"
  - ".trunk/*rc"
  - ".vscode/**"
  - "babel.config.js"
  - "crowdin.yml"
  - "netlify.toml"
  - "tsconfig.json"
area:plugin:
  - "*.zsh"
area:ci:
  - ".github/workflows/*"
