---
blank_issues_enabled: true
contact_links:
  - name: Z-Shell Wiki
    url: https://wiki.zshell.dev
    about: Knowledge base.
  - name: Community Discussions
    url: https://github.com/orgs/z-shell/discussions
    about: Please ask and answer questions here.
  - name: Security report
    url: https://github.com/z-shell/F-Sy-H/security/advisories/new
    about: Report security-sensitive behavior privately.
