[theme]
palette = xterm-256
foreground = #24292f
background = #ffffff
description = GitHub-inspired light theme.

[base]
default          = none
unknown-token    = #82071e,bold
commandseparator = none
redirection      = none
here-string-tri  = #0550ae
here-string-text = bg:#ddf4ff
here-string-var  = #0550ae,bg:#ddf4ff
exec-descriptor  = #7d4e00,bold
comment          = #57606a
correct-subtle   = #ffffff,bg:#0550ae,bold
incorrect-subtle = #ffffff,bg:#82071e,bold
subtle-separator = none
subtle-bg        = bg:#ddf4ff
; secondary        =
recursive-base   = #6639ba

[command-point]
reserved-word  = #6639ba
subcommand     = #0550ae
alias          = #0550ae
suffix-alias   = #0550ae
global-alias   = bg:#fff8c5
builtin        = #0550ae
function       = #0550ae
command        = #0550ae
precommand     = #6639ba
hashed-command = #0550ae
single-sq-bracket = #0550ae
double-sq-bracket = #0550ae,bold
double-paren   = #6639ba

[paths]
path          = #0550ae
pathseparator =
path-to-dir   = #0550ae,underline
globbing      = #116329
globbing-ext  = #7d4e00

[brackets]
paired-bracket = bg:#f6f8fa
bracket-level-1 = #116329
bracket-level-2 = #6639ba
bracket-level-3 = #7d4e00

[arguments]
single-hyphen-option   = #116329
double-hyphen-option   = #116329,bold
back-quoted-argument   = none
single-quoted-argument = #7d4e00
double-quoted-argument = #6639ba
optarg-string          = #6639ba,bold
dollar-quoted-argument = #7d4e00

[in-string]
; backslash in $'...'
back-dollar-quoted-argument           = #116329
; backslash or $... in "..." (i.e. variable in string)
back-or-dollar-double-quoted-argument = #0550ae

[other]
variable             = #82071e
assign               = none
assign-array-bracket = #6639ba
history-expansion    = #82071e,bold

[math]
mathvar = #6639ba
mathnum = #7d4e00
optarg-number = #7d4e00
matherr = #82071e,bold

[for-loop]
forvar = #6639ba
fornum = #7d4e00
; operator
foroper = #6639ba,bold
; separator
forsep = #57606a

[case]
case-input       = #0550ae
case-parentheses = #6639ba
case-condition   = bg:#dafbe1
