[theme]
palette = xterm-256
foreground = #ffffff
background = #000000

[base]
default          = none
unknown-token    = 210,bold
commandseparator = none
redirection      = none
here-string-tri  = 141
here-string-text = bg:19
here-string-var  = 45,bg:19
exec-descriptor  = yellow,bold
comment          = 243
correct-subtle   = bg:55
incorrect-subtle = bg:52
subtle-separator = none
subtle-bg        = bg:17
secondary        = base16
recursive-base   = 190

[command-point]
reserved-word  = 48
subcommand     = 51
alias          = 135
suffix-alias   = 135
global-alias   = bg:19
builtin        = 135
function       = 135
command        = 135
precommand     = 135
hashed-command = 135
single-sq-bracket = 135
double-sq-bracket = 135
double-paren   = 48

[paths]
path          = 82
pathseparator =
path-to-dir   = 82,underline
globbing      = 200
globbing-ext  = 135

[brackets]
paired-bracket = bg:blue
bracket-level-1 = 165
bracket-level-2 = 226
bracket-level-3 = 50

[arguments]
single-hyphen-option   = 45
double-hyphen-option   = 45,bold
back-quoted-argument   = none
single-quoted-argument = 48
double-quoted-argument = 48
optarg-string          = 48
dollar-quoted-argument = 48

[in-string]
; backslash in $'...'
back-dollar-quoted-argument           = 45
; backslash or $... in "..."
back-or-dollar-double-quoted-argument = 45

[other]
variable             = none
assign               = none
assign-array-bracket = 135
history-expansion    = 69,bold

[math]
mathvar = 69,bold
mathnum = 82
optarg-number = 82
matherr = 210

[for-loop]
forvar = none
fornum = 82
; operator
foroper = 48
; separator
forsep = 111

[case]
case-input       = 135
case-parentheses = 141
case-condition   = bg:19
