---
name: Trunk Code Quality

on:
  push:
    branches: [main]
    tags: ["v*.*.*"]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
  workflow_dispatch: {}

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: Trunk Code Quality
    uses: z-shell/.github/.github/workflows/trunk.yml@f09e2cc9cbad2d587eaebfba690f7aad2b3ee80e # main
    with:
      arguments: --no-progress
